
package cn.itcast.ws.jaxws.weather.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterfaceImpl", targetNamespace = "http://server.weather.jaxws.ws.itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterfaceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryName", targetNamespace = "http://server.weather.jaxws.ws.itcast.cn/", className = "cn.itcast.ws.jaxws.weather.server.QueryName")
    @ResponseWrapper(localName = "queryNameResponse", targetNamespace = "http://server.weather.jaxws.ws.itcast.cn/", className = "cn.itcast.ws.jaxws.weather.server.QueryNameResponse")
    @Action(input = "http://server.weather.jaxws.ws.itcast.cn/WebServiceInterfaceImpl/queryNameRequest", output = "http://server.weather.jaxws.ws.itcast.cn/WebServiceInterfaceImpl/queryNameResponse")
    public String queryName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
