
package cn.itcast.ws.jaxws.weather.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceInterfaceImplService", targetNamespace = "http://server.weather.jaxws.ws.itcast.cn/", wsdlLocation = "http://127.0.0.1:12345/weather?wsdl")
public class WebServiceInterfaceImplService
    extends Service
{

    private final static URL WEBSERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICEINTERFACEIMPLSERVICE_QNAME = new QName("http://server.weather.jaxws.ws.itcast.cn/", "WebServiceInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICEINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceInterfaceImplService() {
        super(__getWsdlLocation(), WEBSERVICEINTERFACEIMPLSERVICE_QNAME);
    }

    public WebServiceInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEINTERFACEIMPLSERVICE_QNAME, features);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEINTERFACEIMPLSERVICE_QNAME);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEINTERFACEIMPLSERVICE_QNAME, features);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceInterfaceImpl
     */
    @WebEndpoint(name = "WebServiceInterfaceImplPort")
    public WebServiceInterfaceImpl getWebServiceInterfaceImplPort() {
        return super.getPort(new QName("http://server.weather.jaxws.ws.itcast.cn/", "WebServiceInterfaceImplPort"), WebServiceInterfaceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceInterfaceImpl
     */
    @WebEndpoint(name = "WebServiceInterfaceImplPort")
    public WebServiceInterfaceImpl getWebServiceInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.weather.jaxws.ws.itcast.cn/", "WebServiceInterfaceImplPort"), WebServiceInterfaceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
