package cn.itcast.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-27T22:31:51.628+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://weather.itcast.cn/", name = "weatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebMethod
    @RequestWrapper(localName = "queryWeatherList", targetNamespace = "http://weather.itcast.cn/", className = "cn.itcast.weather.QueryWeatherList")
    @ResponseWrapper(localName = "queryWeatherListResponse", targetNamespace = "http://weather.itcast.cn/", className = "cn.itcast.weather.QueryWeatherListResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<cn.itcast.weather.WeatherModel> queryWeatherList(
        @WebParam(name = "cityName", targetNamespace = "")
        java.lang.String cityName
    );
}
